# 本文件严格区分参数的数据类型，比如 10.0 不能改成 10

[Camera]
    #@bool 是否通过 sn 码查找相机，false 则查找第 0 个
    use_camera_sn = true
    #@string 相机 sn 码
    camera_sn = "00G07828078"
    #@bool 使用从 MVS 导出的配置文件
    use_config_from_file = true
    #@string 配置文件在 config 文件夹中的路径
    config_file_path = "MV-CA016-10UC_00G07828078.mfs"
    #@bool 是否从 Camera.config 中设置参数，会覆盖上文中的文件配置
    use_camera_config = true

[Camera.config]
    #@float 曝光时间 (us)
    ExposureTime = 2500.0
    #@float 增益
    Gain = 16.9
    #@bool 水平翻转
    ReverseX = false
    #@bool 垂直翻转
    ReverseY = false
    #@int 图像宽度
    Width = 1440
    #@string ADC 位深
    ADCBitDepth = "Bits_8"
    #@bool 启用 Gamma 校正
    GammaEnable = false
    #@float 采集帧率
    AcquisitionFrameRate = 200.0
    #@bool 启用帧率限制
    AcquisitionFrameRateEnable = true

[Serial]
    #@string 协议类型: "uart" 或 "usb_bulk"
    protocol = "uart"
    #@bool 打印串口调试信息
    data_print_debug = false
    #@bool 忽略 CRC 校验
    ignore_crc = false
    #@bool 不接串口时使用虚拟数据
    use_fake_serial_data = true
    #@bool IMU 符号修正: yaw 取反
    imu_yaw_negate = false
    #@bool IMU 符号修正: pitch 取反
    imu_pitch_negate = false
    #@bool IMU 符号修正: roll 取反
    imu_roll_negate = true

[Serial.uart]
    #@string 串口设备路径
    port_name = "/dev/ttyUSB0"
    #@int 波特率
    baudrate = 115200

[Serial.usb_bulk]
    # 下面这些参数仅在 protocol = "usb_bulk" 时使用
    vendor_id = "0xa11c"
    product_id = ""
    serial_number = ""
    interface_number = 0
    bulk_in_endpoint = "0x81"
    bulk_out_endpoint = "0x01"
    timeout_ms = 10
    reconnect_interval_ms = 2000
    max_reconnect_attempts = 5

[Serial.fake_data]
    # 虚拟串口数据配置
    # 实际 dart 接收协议只包含 should_detect 和 dart_number

    #@bool 当前是否应该检测
    should_detect = true
    #@int 当前第几枚飞镖，实际串口由电控发送
    dart_number = 2
    allow_fire = true

[TimeSync]
    #@int 相机-IMU 时间偏移 (微秒)
    # 正值: 图像比 IMU 数据晚到达，匹配过去的 IMU
    # 负值: 图像比 IMU 数据早到达，匹配未来的 IMU
    delta_t_us = 4886
